### ISSUE TITLE
我也来开贴玩

### ISSUE THREAD

**Issue by Kinice** [Svtter/Kill-Shift-Space#1]
你说咱开了贴也没别人来讨论，就咱俩啊。

**Comment by Svtter** [comment]
这个本来就是这样啦，也没啥好讨论的

**Comment by vincepeng** [comment]
支持一下64位把.

**Comment by Svtter** [comment]
@vincepeng 64位应该是可以直接使用的，当然，如果你是处女座，你可以打开vs选好64位自己编译一下。但是我个人认为没差的= =。

**Comment by seantw** [comment]
感謝! 在 win10 上這小程式實在太實用了! 解決常不小心按到左邊的 Shift+Space。
但可不可以保留右邊的 Shift+Space 維持切換全半型的功能?

**Comment by Svtter** [comment]
@seantw 感谢你的建议，等我有时间修改一下

**Comment by Svtter** [comment]
@seantw 增加了AHK的方案，应该能够满足你的需求。使用第二种方案需要安装[AutoHotKey](https://autohotkey.com/)，或者使用我编译好的`kill-shift-space.exe`
