### ISSUE TITLE
阅读理解不行，没看明白说的什么，测试之后补充一下，方便大家选择

### ISSUE THREAD

**Issue by luxuxl** [Svtter/Kill-Shift-Space#5]
- GlobalHotkey.exe：禁用 shift + space，即按了没反应，利用 win32API 实现
- Kill-shift-space.exe：禁用 shift + space，即按了没反应，利用 autohotkey 实现
- killshiftspace-map.exe：将 shift + space 映射为 space，即按了是空格，利用 autohotkey 实现

**Comment by Svtter** [comment]
感谢
